### ISSUE TITLE
[BUG] Unused module, but it's actually used in package.json

### ISSUE THREAD

**Issue by eggsy** [Timeraa/TS-DevScript#4]
Hey Tim,

I have been using the module for a long time now and I just updated it to the latest version and saw the unused dependency check feature. It's neat and I love it but there's one thing, it doesn't look for the scripts in `package.json`. I use a module to move files from a location to a different location with that package but DevScript says I don't use it (and I don't, at least it is never imported in code).

![image](https://user-images.githubusercontent.com/13917975/103831185-5e8ec800-5030-11eb-8560-734141834e39.png)
![image](https://user-images.githubusercontent.com/13917975/103831203-68b0c680-5030-11eb-96a6-a9d4002f567c.png)

**Comment by Timeraa** [comment]
I'll see what I can do 😉

**Comment by Bas950** [comment]
I have the same sort of error, one of my dependencies uses needs an @types for it work, else it errors out. But now I get unused dev dependency.

**Comment by Timeraa** [comment]
Seems to be an issue from depcheck itself > depcheck/depcheck#584

**Comment by Timeraa** [comment]
Closing as this should be fixed, since we now use our own module `autopm`
